import argparse
import sqlite3
import httpx

from sqlite3.dbapi2 import Connection


def missingpuididentifier(file: str) -> None:
    """
    Takes a path to a database generated by Digiarch

    Prints a list of every puid in the given database that isn't
      currently found within our convertool .json files
    """
    # read in our .json files as dicts.
    # pull them from our convertool github to make sure they're up to date
    response_convert = httpx.get(
        "https://raw.githubusercontent.com/aarhusstadsarkiv/reference-files/main/to_convert.json"
    )
    response_convert_unarchiver = httpx.get(
        "https://raw.githubusercontent.com/aarhusstadsarkiv/reference-files/main/to_convert_unarchiver.json"
    )
    response_convert_symphovert = httpx.get(
        "https://raw.githubusercontent.com/aarhusstadsarkiv/reference-files/main/to_convert_symphovert.json"
    )
    response_ignore = httpx.get(
        "https://raw.githubusercontent.com/aarhusstadsarkiv/reference-files/main/to_ignore.json"
    )

    convert_dict: dict = response_convert.json()
    # print(f"length of convert before unarchiver: {len(convert_dict)}")
    convert_unarchiver_dict: dict = response_convert_unarchiver.json()
    convert_dict.update(convert_unarchiver_dict)
    # print(f"length of convert after unarchiver: {len(convert_dict)}")
    convert_symphovert_dict: dict = response_convert_symphovert.json()
    convert_dict.update(convert_symphovert_dict)
    # print(f"length of convert after symphovert: {len(convert_dict)}")

    ignore_dict: dict = response_ignore.json()
    unidentified_files: int = 0

    # Query _Signaturecount-view from files.db
    # Print every puid currently not in the .json-files
    print(
        "Currently unhandled fileformats in the supplied files.db:",
        flush=True,
    )
    try:
        con: Connection = sqlite3.connect(
            "file:" + file + "?mode=ro", uri=True
        )
        for puid, signature, count in con.execute(
            "SELECT puid, signature, count FROM _SignatureCount"
        ):
            if puid is None:
                unidentified_files = count
            elif puid not in convert_dict and puid not in ignore_dict:
                print(
                    f"PUID: {puid}\tCount: {count}\t {signature}",
                    flush=True,
                )

        if unidentified_files:
            print(
                f"There was also {unidentified_files} unidentified file(s)",
                flush=True,
            )

    except sqlite3.DatabaseError:
        print(
            "Error: "
            + file
            + " isn't a path to a valid Digiarch-produced database!"
        )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "file",
        help="the path to the database generated by Digiarch that's "
        + "to be compared with our current convertool json files",
        type=str,
    )
    args: argparse.Namespace = parser.parse_args()
    missingpuididentifier(args.file)


if __name__ == "__main__":
    main()
