import argparse
import sqlite3
import httpx

from sqlite3.dbapi2 import Connection
from typing import Dict


def missingpuididentifier(file: str) -> None:
    """
    Takes a path to a database generated by Digiarch

    Prints a list of every puid in the given database that isn't
      currently found within our convertool .json files
    """
    # read in our .json files as dicts.
    # have to pull them from our convertool github to make sure they're up to date
    response_convert = httpx.get(
        "https://raw.githubusercontent.com/aarhusstadsarkiv/"
        "convertool/master/data/to_convert2.json"
    )
    response_ignore = httpx.get(
        "https://raw.githubusercontent.com/aarhusstadsarkiv/"
        "convertool/master/data/to_ignore.json"
    )

    convert_dict: Dict = response_convert.json()
    ignore_dict: Dict = response_ignore.json()
    unidentified_files: int = 0

    # make a query to our database to get all the puids from the signaturecount view
    # then iterate thru the result, printing every puid currently missing from the .jsons
    print(f"Fileformats in the supplied files.db that we are currently unable to handle:", flush=True)
    try:
        con: Connection = sqlite3.connect(
            "file:" + file + "?mode=ro", uri=True
        )
        for puid, signature, count in con.execute(
            "SELECT puid, signature, count FROM _SignatureCount"
        ):
            if puid is None:
                unidentified_files += 1 
            elif puid not in convert_dict and puid not in ignore_dict:
                print(f"PUID: {puid}\tCount: {count}\t ({signature})", flush=True)

        if unidentified_files:
            print(f"There was also {unidentified_files} unidentified file(s)", flush=True)

    except sqlite3.DatabaseError:
        print(
            "Error: "
            + file
            + " isn't a path to a valid Digiarch-produced database!"
        )


parser = argparse.ArgumentParser()
parser.add_argument(
    "file",
    help="the path to the database generated by Digiarch that's "
    + "to be compared with our current convertool json files",
    type=str,
)
args: argparse.Namespace = parser.parse_args()
missingpuididentifier(args.file)
